addons: 
  apt: 
    packages: 
      - chromium-chromedriver
  chrome: stable
before_install: 
  - wget https://chromedriver.storage.googleapis.com/80.0.3987.106/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo apt-get install libnss3
  - cp chromedriver /usr/local/bin/.
  - chmod +x mvnw
dist: trusty
jdk: 
  - oraclejdk15
language: java
sudo: true