addons: 
  apt: 
    packages: 
      - chromium-chromedriver
  chrome: stable
before_install: 
  - "wget https://chromedriver.storage.googleapis.com/80.0.3987.106/chromedriver_linux64.zip"
  - "unzip chromedriver_linux64.zip"
  - "sudo apt-get install libnss3"
  - "sudo cp chromedriver /usr/local/bin/."
  - "sudo chmod +x /usr/local/bin/chromedriver"
dist: trusty
install: 
  - "mvn -N io.takari:maven:wrapper"
  - "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
jdk: 
  - oraclejdk15
language: java
sudo: required